# Setup
title:               Aroha Dev
tagline:             'Development with Love'
description:         'mobile app development'
url:                 http://aroha.dev
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Lee Jordan
  url:               https://twitter.com/geraldleejordan
  email:             geraldleejordan@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
